on:
  push:
    branches:
      - release-please

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: "packages/ui"
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: node
          config-file: release-please-config.json
      - run: echo '${{ toJSON(steps.release.outputs) }}'
      
      - name: Enable Pull Request auto merge
        if: steps.release.outputs.releases_created
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ steps.release.outputs.pr.number }}
          TITLE: '[UI] Automatic Release with release-please'
        shell: bash
        run:
          gh pr merge -R ${{ github.repository }} --merge --auto ${{ env.pr_number }} -b "" -t '⇄ PR-#${{ env.pr_number }} | ${{ env.TITLE }}'
     